version: "3"

services:
  rosmaster:
    image: ros:kinetic-ros-core
    container_name: rosmaster
    hostname: rosmaster
    ports:
      - "11311:11311"
    command: roscore

  rrbot-gazebo:
    depends_on:
      - "rosmaster"
    image: prince/ros-kinetic-desktop-no-vnc:latest
    container_name: rrbot-gazebo
    hostname: rrbot-gazebo
    tty: true
    devices: 
      - /dev/dri:/dev/dri
    environment:
      - "DISPLAY=192.168.1.12:0"
      - "ROS_HOSTNAME=rrbot-gazebo"
      - "ROS_MASTER_URI=http://rosmaster:11311"
      - "QT_X11_NO_MITSHM=1"
    volumes: 
      - ./logs/rrbot-gazebo:/root/.ros/log
      - /tmp/.X11-unix:/tmp/.X11-unix
    
  rrbot-control:
    depends_on:
      - "rosmaster"
      - "rrbot-gazebo"
    image: prince/ros-kinetic-desktop-no-vnc
    container_name: rrbot-control
    hostname: rrbot-control
    tty: true
    environment:
      - "ROS_HOSTNAME=rrbot-control"
      - "ROS_MASTER_URI=http://rosmaster:11311"
    command: "roslaunch rrbot_control rrbot_control.launch"

  rrbot-talker:
    depends_on:
      - "rosmaster"
      - "rrbot-gazebo"
      - "rrbot-control"
    image: prince/ros-rrbot-control:latest
    container_name: rrbot-talker
    hostname: rrbot-talker
    environment:
      - "ROS_HOSTNAME=rrbot-talker"
      - "ROS_MASTER_URI=http://rosmaster:11311"
    command: rosrun mypkg task0_rrbot_pub.py