version: "3"

services:
  rosmaster:
    image: ros:kinetic-ros-core
    container_name: rosmaster
    command: roscore
    environment:
      - "ROS_IP=172.19.0.100"
    networks:
      ros_net:
        ipv4_address: 172.19.0.100
    ports:
      - "11311:11311"
      - "33690:33690"

  talker:
    depends_on:
      - "rosmaster"
    image: prince/ros-talker-listener
    container_name: talker
    environment:
      - "ROS_IP=172.19.0.101"
      - "ROS_MASTER_URI=http://172.19.0.100:11311"
    command: rosrun mypkg task0_pub.py
    networks:
      ros_net:
        ipv4_address: 172.19.0.101

  listener:
    depends_on:
      - "rosmaster"
    image: prince/ros-talker-listener
    container_name: listener
    environment:
      - "ROS_IP=172.19.0.102"
      - "ROS_MASTER_URI=http://172.19.0.100:11311"
    command: rosrun mypkg task0_sub.py
    networks:
      ros_net:
        ipv4_address: 172.19.0.102

networks:
  ros_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/24
          gateway: 172.19.0.1
